## Helm chart values - https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  additionalArguments:
    # Added to enable exposing metrics for prometheus
    # - "--metrics.prometheus=true"
    - "--providers.kubernetesingress=true"
    # you need to manually set this IP to the incoming public IP that your ingress resources would use. Note it only affects
    # status and kubectl UI, and doesn't really do anything It could even be left out https://github.com/containous/traefik/issues/6303
    - "--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1"
    # - "--providers.kubernetesingress.ingressendpoint.hostname=localhost"
  logs:
    general:
      level: DEBUG
    access:
      enabled: true
      format: json
      filePath: /var/log/traefik/access.log
      fields:
        headers:
          defaultmode: keep
      # filters:

  deployment:
    # replicas: 3
    ### uncomment to enable container that tails access log
    # additionalContainers:
    #   - name: tail-accesslogs
    #     image: busybox
    #     args: [ "/bin/sh", "-c", "tail -n+1 -F /var/log/traefik/access.log" ]
    #     volumeMounts:
    #       - name: logs
    #         mountPath: /var/log/traefik
    additionalVolumes:
    - name: logs
  additionalVolumeMounts:
  - name: logs
    mountPath: /var/log/traefik
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      # matchRule: (Host(`traefik.dev.local`) && PathPrefix(`/dashboard`)) || (Host(`traefik.dev.local`) && PathPrefix(`/api`))
      # tls:
      #   certResolver: default-root-cert-issuer
      #   secretName: traefik-server-tls
    healthcheck:
      enabled: true
  # metrics:
  #   prometheus:
  #     entryPoint: metrics