## Official configuration - 
## Helm chart values - https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  enabled: true
  ## https://dexidp.io/docs/configuration/
  config:
    issuer: https://dex.dev.local
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    ## https://dexidp.io/docs/connectors/
    connectors:
      - type: mockCallback
        id: mock
        name: Mock
      # - type: oidc
      #   id: zitadel
      #   name: zitadel
      #   config:
      #     clientID: "264743436580618784@k8s"
      #     clientSecret: 
      #     redirectURI: https://dex.dev.local/callback
      #     issuer: https://zitadel.dev.local
      #     # TODO https://github.com/dexidp/dex/pull/3188
      #     # enablePKCE: true
      #     scopes:
      #       - openid
      #       - profile
      #       - email
      #       - groups
  #   staticClients:
  #     - id: grafana-sso
  #       name: Grafana
  #       redirectURIs:
  #         - 'https://grafana.khuedoan.com/login/generic_oauth'
  #       secretEnv: GRAFANA_SSO_CLIENT_SECRET
  #     - id: gitea
  #       name: Gitea
  #       redirectURIs:
  #         - 'https://git.khuedoan.com/user/oauth2/Dex/callback'
  #       secretEnv: GITEA_CLIENT_SECRET
  # envFrom:
  #   - secretRef:
  #       name: dex-secrets
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hosts:
      - host: &host dex.dev.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-general-tls
        hosts:
          - *host
  serviceMonitor:
    enabled: true