## Official configuration - 
## Helm chart values - https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  enabled: true
  ## https://dexidp.io/docs/configuration/
  config:
    issuer: https://dex.dev.local
    ## TODO move storage to postgres. The storage configuration determines where dex stores its state.
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    ## https://dexidp.io/docs/connectors/
    connectors:
      # - type: mockCallback
      #   id: mock
      #   name: Mock
      - type: oidc
        id: zitadel
        name: zitadel
        config:
          clientID: $ZITADEL_CLIENT_ID
          clientSecret: $ZITADEL_CLIENT_SECRET
          redirectURI: https://dex.dev.local/callback
          issuer: https://zitadel.dev.local
          response_type: code
          insecureSkipVerify: true # ignore SSL verification
          # insecureSkipEmailVerified: true
          scopes:
            - openid
            - profile
            - email
            - groups
          userNameKey: zitadel:name
          claimMapping:
            userNameKey: name

    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.dev.local/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-credential
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hosts:
      - host: &host dex.dev.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-general-tls
        hosts:
          - *host
  serviceMonitor:
    enabled: true