## Official configuration - 
## Helm chart values - https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  enabled: true
  # https://dexidp.io/docs/configuration/
  config:
    issuer: https://dex.dev.local
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
  #   # https://dexidp.io/docs/connectors/
  #   connectors:
  #     - type: oidc
  #       id: kanidm
  #       name: Kanidm
  #       config:
  #         clientID: $KANIDM_CLIENT_ID
  #         clientSecret: $KANIDM_CLIENT_SECRET
  #         redirectURI: https://dex.khuedoan.com/callback
  #         issuer: https://auth.khuedoan.com/oauth2/openid/dex
  #         # TODO https://github.com/dexidp/dex/pull/3188
  #         # enablePKCE: true
  #         scopes:
  #           - openid
  #           - profile
  #           - email
  #           - groups
  #   staticClients:
  #     - id: grafana-sso
  #       name: Grafana
  #       redirectURIs:
  #         - 'https://grafana.khuedoan.com/login/generic_oauth'
  #       secretEnv: GRAFANA_SSO_CLIENT_SECRET
  #     - id: gitea
  #       name: Gitea
  #       redirectURIs:
  #         - 'https://git.khuedoan.com/user/oauth2/Dex/callback'
  #       secretEnv: GITEA_CLIENT_SECRET
  # envFrom:
  #   - secretRef:
  #       name: dex-secrets
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hosts:
      - host: &host dex.dev.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-general-tls
        hosts:
          - *host
