## Official configuration - 
## Helm chart values - https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
keycloak:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
  auth:
    adminUser: admin
    existingSecret: keycloak-credentials-secret
    passwordSecretKey: admin-password
  postgresql:
    enabled: true
    auth:
      ## Password for the "postgres" admin user
      # postgresPassword: "@temp12postgresql"
      username: bn_keycloak
      # password: "@temp12postgresql"
      database: bitnami_keycloak
      existingSecret: keycloak-credentials-secret
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
        # replicationPasswordKey: postgres_replication_password
    architecture: standalone
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hostname: &host identity.dev.local
    extraTls:
      - secretName: keycloak-server-tls
        hosts:
          - *host