## Official configuration - 
## Helm chart values - https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
keycloak:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
  postgresql:
    enabled: true
    auth:
      username: bn_keycloak
      password: "@pisix123/postgresql"
      database: bitnami_keycloak
      ## Password for the "postgres" admin user
      # postgresPassword: ""
      # existingSecret: ""
    architecture: standalone
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hostname: &host identity.dev.local
    extraTls:
      - secretName: keycloak-server-tls
        hosts:
          - *host