promtail:
  enabled: true
  serviceMonitor:
    enabled: true
  config:
    clients:
      - url: http://loki-loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push
      # - url: http://loki-gateway.svc.cluster.local/loki/api/v1/push