# https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#configure-promtail
promtail:
  enabled: true
  serviceMonitor:
    enabled: true
  config:
    clients:
      - url: http://loki-loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push
    snippets:
      extraScrapeConfigs: |
        - job_name: auditlogs
          static_configs:
            - targets:
                - localhost
              labels:
                job: auditlogs
                host: ${HOSTNAME}
                __path__: /var/log/audit/kube/*.log
