# ## TODO replace with external secrets
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: dex-credential
# stringData:
#   ZITADEL_CLIENT_ID: 
#   ZITADEL_CLIENT_SECRET: 
#   GRAFANA_SSO_CLIENT_SECRET: 264760171249599008@testproject
#   ARGOCD_SSO_CLIENT_SECRET: 133880978119599112@argoproject