ingress-nginx:
  enabled: false
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    # extraArgs:
    #   --enable-ssl-passthrough
  # tcp:
  #   22: gitea/gitea-ssh:22
