grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
      # nginx.ingress.kubernetes.io/use-regex: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /grafana
    hosts:
      - &host argocd.dev.local
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      # the sidecar will search for dashboard config-maps inside this namespace.
      searchNamespace: ALL
    datasources:
      enabled: true
      # the sidecar will search for datasource config-maps inside this namespace.
      searchNamespace: ALL
  # envFromSecret: grafana-secrets
  ## Grafana's primary configuration ref: http://docs.grafana.org/installation/configuration/
  # grafana.ini:
  #   server:
  #     root_url: https://grafana.dev.local
