# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "loki.fullname" . }}-grafana-datasource
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "loki.labels" . | nindent 4 }}
#     # app: {{ include "loki.compactorFullname" . }}
#     # chart: {{ template "loki.chart" . }}
#     # release: {{ .Release.Name }}
#     # heritage: {{ .Release.Service }}
#     grafana_datasource: "1"
# data:
#   datasource-loki-distributed.yaml: |-
#     apiVersion: 1
#     datasources:
#     - name: Loki
#       type: loki
#       access: proxy
#       url: http://{{(include "loki.compactorFullname" .)}}:3100
#       version: 1
#       isDefault: false