apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-grafana-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "loki.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://{{(include "loki.gatewayFullname" .)}}:3100
      isDefault: false