---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-app-user
type: kubernetes.io/basic-auth
data:
  password: VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: YXBw
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-superuser
type: kubernetes.io/basic-auth
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
spec:
  instances: 3
  # primaryUpdateStrategy: unsupervised
  # postgresql:
  #   parameters:
  #     shared_buffers: 256MB
  #     pg_stat_statements.max: '10000'
  #     pg_stat_statements.track: all
  #     auto_explain.log_min_duration: '10s'
  #   pg_hba:
  #     - host all all 10.244.0.0/16 md5
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cloudnative-pg-app-user
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-superuser
  storage:
    # storageClass: standard
    size: 2Gi