---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
spec:
  ## Number of instances required in the cluster. kubectl get cluster -n cloudnative-pg 
  instances: 2
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cloudnative-pg-cluster-app
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-cluster-superuser
  storage:
    # storageClass: standard
    size: 1Gi
  monitoring:
    enablePodMonitor: true