---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-app-user
type: kubernetes.io/basic-auth
data:
  password: VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: YXBw
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-superuser
type: kubernetes.io/basic-auth
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
spec:
  ## Number of instances required in the cluster. kubectl get cluster -n cloudnative-pg 
  instances: 2
  # bootstrap:
  #   initdb:
  #     database: app
  #     owner: app
  #     secret:
  #       name: cloudnative-pg-app-user
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-superuser
  storage:
    # storageClass: standard
    size: 1Gi
  monitoring:
    enablePodMonitor: true