## TODO replace with external secrets
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: grafana-credential
stringData:
  admin-user: admin@grafana.com
  admin-password: Admin@grafana123.com
  GRAFANA_SSO_CLIENT_SECRET: 264760171249599008@testproject