---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credential
spec:
  target:
    name: grafana-credential
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: |-
          {{ `{{ .username }}` }}
        admin-password: |-
          {{ `{{ .password }}` }}
        GRAFANA_SSO_CLIENT_SECRET: |-
          {{ `{{ .sso_client_secret }}` }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: grafana
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: grafana
        property: password
    - secretKey: sso_client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: grafana
        property: sso_client_secret